server:
  port: ${PORT:5544}
spring:
  application:
    name: cyber-done-device-microservice
    version: @version@
  datasource:
    name: postgres
    password: ${CDDS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/cdds
  flyway:
    user: postgres
    password: ${CDDS_DB_PASSWORD}
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLInnoDBDialect

security:
  jwt-secret: ${JWT_SECRET}

mqtt:
  username: ${CDDS_MQTT_USERNAME}
  password: ${CDDS_MQTT_PASSWORD}
  clean-session: false
  connection-timeout: 10
  auto-reconnect: true
  max-reconnect-delay-ms: 300000
  qos: 2
  max-in-flight-messages: 100
  client-name: ${spring.application.name}-${spring.application.version}-client
  client-url: ${CDDS_MQTT_LOCAL_SERVER_URL}

device:
  control:
    send-command:
      message-quality-of-service: 1
      message-retained: false
      retry-amount: 2
      start-delay-ms: 0
      period-ms: 1000