server:
  port: ${PORT:5555}
  servlet:
    context-path:
spring:
  application:
    name: cyber-done-device-microservice
    version: @version@
  profiles:
    active: dev
  datasource:
    username: ${CDDS_DB_USERNAME}
    password: ${CDDS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${CDDS_DB_URL}
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLInnoDBDialect
security:
  aes-key: ${CDDS_MESSAGE_ENCRYPTIN_SECRET}
  jwt-secret: ${JWT_SECRET}
  callback:
    show-decrypted-message:
      hydroponic-v1-settings: true
      autotime: false
mqtt:
  username: ${CDDS_MQTT_USERNAME}
  password: ${CDDS_MQTT_PASSWORD}
  clean-session: false
  connection-timeout: 10
  auto-reconnect: true
  max-in-flight-messages: 100
  client:
    name: CDDS
    url: ${CDDS_MQTT_SERVER_URL}
    quality-of-service: 2