server:
  port: ${PORT:5544}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.100:8761/eureka/
  instance:
    hostname: 192.168.1.100
spring:
  application:
    name: cyber-done-device-microservice
    version: @version@
  profiles:
    active: dev
  datasource:
    username: ${CDDS_DB_USERNAME}
    password: ${CDDS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${CDDS_DB_URL}
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLInnoDBDialect
security:
  aes-key: ${CDDS_MESSAGE_ENCRYPTIN_SECRET}
  jwt-secret: ${JWT_SECRET}
  callback:
    show-decrypted-message:
      hydroponic-v1-settings: false
      autotime: false
mqtt:
  username: ${CDDS_MQTT_USERNAME}
  password: ${CDDS_MQTT_PASSWORD}
  clean-session: false
  connection-timeout: 10
  auto-reconnect: true
  max-in-flight-messages: 100
  client-name: CDDS
  client-url: ${CDDS_MQTT_SERVER_URL}

device:
  control:
    send-command:
      message-quality-of-service: 2
      message-retained: true
      retry-amount: 2
      start-delay-ms: 0
      period-ms: 1000
